apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: streaming-server
  name: streaming-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streaming-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: streaming-server
    spec:
      containers:
        - image: codeworksio/streaming-server
          name: streaming-server
          ports:
            - containerPort: 1935
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/streaming
              name: streaming-server-claim0
      restartPolicy: Always
      volumes:
        - name: streaming-server-claim0
          persistentVolumeClaim:
            claimName: streaming-server-claim0
status: {}
